#!/bin/bash
# HOOK - Teste si le poste est connu. exit 0 si OUI, 1 sinon
#
# NOTE : foguefi "source" automatiquement fog/lib/funcs.sh
. /usr/share/foguefi/funcs.sh

if [ "$(hostname -s)" == "$C_UNKNOWN_COMPUTER" ]; then
    exit 1
else
    exit 0
fi
