#!/bin/bash

# NOTE : foguefi "source" automatiquement fog/lib/funcs.sh
. /usr/share/foguefi/funcs.sh

# ===== Join Multicast session
PROCESS_JointMulticast
# Quitte immédiatement le menu ; fos-manager prends le relai sur la gestion des tâches...
exit 123
