#!/bin/bash

# NOTE : foguefi "source" automatiquement fog/lib/funcs.sh
. /usr/share/foguefi/funcs.sh

# ===== Update product key
PROCESS_UpdateKey
# Quitte immédiatement le menu ; fos-manager prends le relai sur la gestion des tâches...
exit 123
