#!/bin/bash
#
# *** This tool download packages && dependancies from a specific repository
#
# @category FOGStub
# @package  FOGUefi
# @author   Yusuph Wickama <yusuph.wickama@wickerlabs.com>
# @author   Alexandre Botzung <alexandre.botzung@grandest.fr>
# @license  http://opensource.org/licenses/gpl-3.0 GPLv3
# @link     https://github.com/yusuphwickama
# @link     https://github.com/abotzung/foguefi
#
#
# This tool download packages && dependancies from a specific repository (Ubuntu Lunar distro)
#
#
export LANG=C 
# check for provided arguments
if [[ $# -lt 1 ]]; then
    echo "[!] No package name provided"
    exit
fi

# TO_KEEP="linux-image;linux-modules;signed"
#
# Environment parameters :
#
# pkgdl_keeppkg       -> Search $needle in package dependancies. If $needle found, keep the package, else ignored. If $needle if empty, keep all packages.
#                          needle separated with semicolon. Eg: "linux-image;linux-modules;signed"
# export pkgdl_keeppkg="linux-image;linux-modules;signed"


aptsrc=$(mktemp)
chmod 0777 "$aptsrc"
echo 'deb [trusted=yes] http://cz.archive.ubuntu.com/ubuntu lunar main' > "$aptsrc"
apt_global_parameter='-o Dir::Etc::sourcelist='${aptsrc}' -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"'
# Update listing (IMPORTANT!)
apt update $apt_global_parameter &> /dev/null



package="$1"
filename="deb.list"
fname="complete_deb.txt"
gcount=$(apt-cache depends ${package} $apt_global_parameter| grep -v "<" | grep -icw "Depends:")
it=0
masterlist="dependencies_master_$RANDOM.mlist"

# colors
black=0; red=1; green=2; yellow=3; blue=4; magenta=5; cyan=6; white=7;

### Start function declarations

# prints the banner
function print_banner {
    tput setaf 3
    echo "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
    echo "|  P a c k a g e  D o w n l o a d e r  v 1.4.1  |"
    echo "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
    echo "--------------- Created by Wick3rman ------------"
    echo "--- Modified by Alexandre BOTZUNG ---------------"
    echo "---------------- alexandre.botzung@grandest.fr --"
    echo ""
    [ -z "$pkgdl_keeppkg" ] && echo '[i] Keeping all packages by default'
    tput setaf 7
}

# prints a message with a given color.
function printclr {
	# $1 - Color code
	# $2 - Message
    tput setaf $1
    echo -ne "$2"
    tput sgr0
}

if [[ ${gcount} -eq 0 ]]; then
    echo "[+] Verify the package name using '$(printclr ${cyan} "apt search")' and try again"
    exit
fi

# check for internet connectivity
wget -q --tries=3 --timeout=3 --spider https://www.apple.com
if [[ $? -ne 0 ]]; then
    # Exit code not 0
    echo "$(printclr ${red} "No connection, check your internet and try again")"
    exit
fi

# reset the timer
function start_timer {
    SECONDS=0
}

# prints time elapsed since `start_timer`
function get_elapsed_time {
	duration=$SECONDS
	min=$(($duration/60))
	sec=$((duration % 60))
	[[ ${min} -eq 0 && ${sec} -gt 0 ]] && echo "$sec Seconds"
	[[ ${min} -gt 0 && ${sec} -gt 0 ]] && echo "${min}m ${sec}s"
	[[ ${min} -eq 0 && ${sec} -eq 0 ]] && echo "${sec}s"
}

# check if a dependency(package) is not present in the masterlist
function is_not_present {
    # $1 package name
    echo $(cat ${masterlist} | grep -ic "$1")
}

# add a dependecy(package) to the masterlist
function add_to_master_list {
    # $1 package name
    
	presr=$(is_not_present "$1")
	if [[ ${presr} -eq 0 ]]; then
		echo "$1" >> ${masterlist}
		echo "[-] Added $(printclr ${cyan} "$1") to dependency list"
	fi
}

# checks if the last command was successful
function check_if_successful {
    # $1 - Command exit code
    # $2 - Message

    if [[ $1 -eq 0 ]]; then
        # Command success
        tput cuu1
        echo "$2 $(printclr ${green} "[OK]")"
    else
        # Command failed
        tput cuu1
        echo "$2 $(printclr ${red} "[x]")"
    fi
}

# downloads package and dependencies
function download_packages {
    # $1 - File with packages listed

    # Append the main package to file
    echo "${package}" >> $1
    add_to_master_list ${package}
    # Iterate through the list and download each dependency
    while read -r line
    do
        name="$line"
        
        echo "[-] Downloading: $(printclr ${cyan} "$name")"
        # *** ICI débute le traitement de la conservation des paquets ***
        
		internal_keep_package="0"
		if [ ! -z "$pkgdl_keeppkg" ]; then
			oldIFS=$IFS
			IFS=';'
			for expr in $pkgdl_keeppkg
			do
					if [[ "$name" == *"$expr"* ]]; then
							internal_keep_package="1"
					fi
			done
			IFS=$oldIFS
		else
			internal_keep_package="1"
		fi
		if [ "$internal_keep_package" != "0" ]; then
			apt-get download "$name" ${apt_global_parameter} &> /dev/null

			if [[ $? -eq 0 ]]; then
				# Download success
				tput cuu1
				echo "$(tput setaf 7)[-] Downloading: $(printclr ${cyan} "$name") $(printclr ${green} "[OK]")"
			else
				# Download failed
				tput cuu1
				echo "$(tput setaf 7)[-] Downloading: $(printclr ${cyan} "$name") $(printclr ${red} "[x]")"
			fi
		else
			# Download failed
			tput cuu1
			echo "$(tput setaf 7)[-] Downloading: $(printclr ${cyan} "$name") $(printclr ${yellow} "[SKIP]")"
		fi

    done < "$1"
}

# convert deb compressed with zstd to xz compression
function convert_deb {
	shopt -s nullglob
	for f in *.deb
	do
		if [ -f "$f" ]; then
			IS_COMPRESSED_WITH_ZSTD=$(file "$f" |grep -icws "data compression zst")
			if [ "$IS_COMPRESSED_WITH_ZSTD" != "0" ]; then
				echo "Converting $f to xz format..."
				# https://unix.stackexchange.com/a/745467
				# TODO : Implement a function to test dpkg current version (https://tracker.debian.org/news/1407587/accepted-dpkg-12118-source-into-unstable/)
				#         & and don't convert packages if dpkg natively supports it.
				# Extract files from the archive
				ar x "$f"
				# Remove old archive (compressed with zstd)
				rm "$f"
				# Uncompress zstd files an re-compress them using xz
				zstd -d < control.tar.zst | xz > control.tar.xz
				zstd -d < data.tar.zst | xz > data.tar.xz
				# Re-create the Debian package
				ar -m -c -a sdsd "$f" debian-binary control.tar.xz data.tar.xz
				# Clean up
				rm debian-binary control.tar.xz data.tar.xz control.tar.zst data.tar.zst
				tput cuu1
				echo "$(tput setaf 7)[-] Conversion successful: $(printclr ${cyan} "$f") $(printclr ${green} "[OK]")"
			else
				echo "$(tput setaf 7)[-] Already in xz format: $(printclr ${cyan} "$f") $(printclr ${yellow} "[SKIP]")"
			fi
		else
            echo "$(tput setaf 7)[-] Error when accessing file : $(printclr ${cyan} "$f") $(printclr ${red} "[Conversion failed]")"
        fi
	done
	# unset it now
	shopt -u nullglob
}

# gets dependencies and append them to package list file (deb.list)
function get_dependencies {
    # $1 package name
    p1="$1"
    apt-cache depends ${p1} ${apt_global_parameter} | grep -v "<" | grep -w "Depends:" > "${p1}_${filename}"

    sed -i -e 's/[<>|:]//g' "${p1}_${filename}"
    sed -i -e 's/Depends//g' "${p1}_${filename}"
    sed -i -e 's/ //g' "${p1}_${filename}"

    # Local count
    lcount=$(apt-cache depends ${p1} ${apt_global_parameter}| grep -v "<" | grep -icw "Depends:")
    lit=0

    while [ ${lit} -lt ${lcount} ]
    do
        read -r line
        name="$line"
        # Add dependency if not in the master list.
        if [[ $(is_not_present "$name") -eq 0 ]]; then
            add_to_master_list ${name}
            get_dependencies ${name}
        fi
        # lit++
        lit=$(expr ${lit} + 1)
    done < "$1_$filename"
}

# gets dependencies for a package.
function get_global {
    # $1 package name

    echo "$(tput setaf 7)[-] Found $gcount dependencies for:$(tput setaf 6) $1 $(tput setaf 7)"
    # Store all dependencies to file.
    apt-cache depends $1 ${apt_global_parameter}| grep -v "<" | grep -w "Depends:" > "$1_$filename"
    # Clean file from unnecessary characters.
    sed -i -e 's/[<>|:]//g' "$1_$filename"
    sed -i -e 's/Depends//g' "$1_$filename"
    sed -i -e 's/ //g' "$1_$filename"

    while [ ${it} -lt ${gcount} ]
    do
        while read -r line
        do
            name="$line"
            round=$(expr ${it} + 1)

            if [[ $( echo ${name} | grep -v "<" | grep -c -w "Depends:") -lt 1 ]]; then
                if [[ $(is_not_present "$name") -eq 0 ]]; then
                    #echo "[-] Adding ${name} to masterlist"
                    add_to_master_list ${name}
                    get_dependencies ${name}
                fi
            fi
            it=$(expr ${it} + 1)
        done < "$1_$filename"
    done
}

### End function declarations

### Start main
print_banner
start_timer

# create directory with package name
#mkdir "$package" &> /dev/null


[[ ! -d "debs" ]] && mkdir "debs" &> /dev/null
[[ -d "debs" ]] && true

if [[ $? -eq 0 ]]; then
    echo "$(printclr ${green} "[+] Created directory $(printclr ${cyan} "$package")")"
    #cd "$package"
	cd "debs"


    # create masterlist file
    touch ${masterlist}

    # get dependencies for package and populate masterlist
    get_global "$package"

    # Sort and remove duplicates
    echo "" >> ${fname}
    sort *.list | uniq > ${fname}

    # read the masterlist to get child dependencies
    echo "[++] Checking for child dependencies"
    while read -r line
    do
        name="$line"
        # check if is package name
        if [[ $( echo ${name} | grep -v "<" | grep -icw "Depends:") -lt 1 ]]; then
            #echo "[$] Round $round:$(tput setaf 6) $name $(tput setaf 7)"
            pre=$(cat ${masterlist} | grep -ic "$name")

            #echo "Pret: $pre"
            if [ ${pre} -eq 0 ]; then
                get_dependencies ${name}
                add_to_master_list ${name}
            fi
        fi
        # it++
        it=$(expr ${it} + 1)
    done < "$fname"

    # delete all list files
    rm *.list

    # download packages from masterlist
    download_packages ${masterlist}

    # delete *.deb.list file
    rm ${fname}
    
    # ICI, je dois mettre mon algo de conversion

	convert_deb

    # package downloaded packages in a Tarball
    #echo "[-] Packaging downloaded packages to $(printclr ${cyan} "$package.tar.gz")"
    cd ..

    # use tar to compress and package.
    ##tar -zcvf "./$package.tar.gz" "$package/" &> /dev/null

    # [Check] packaging success
    ##check_if_successful $? "[-] Packaging downloaded packages to $(printclr ${cyan} "$package.tar.gz")"

    ##echo "[-] Removing original directory"
    ##rm -r "./$package/"
    # [Check] if directory was removed
    ##check_if_successful $? "[-] Removing original directory "
    

    echo "$(printclr ${green} "[-] Operations completed in $(printclr ${yellow} "$(get_elapsed_time)")" )"
else
    echo "$(printclr ${red} "[!]")  Failed to create directory $(printclr ${cyan} "$package"). Delete existing directory or make sure you have sufficient permissions."
fi
rm "$aptsrc"
### End main
