#!/bin/sh
# @category FOGStubmenu
# @package  FOGUefi
# @author   Alexandre Botzung <alexandre.botzung@grandest.fr>
# @license  http://opensource.org/licenses/gpl-3.0 GPLv3
# @link     https://fogproject.org
#
echo "Mounting minimal fs..."
mount -t devtmpfs none /dev >> /dev/null 2>&1
mkdir /dev/pts >> /dev/null 2>&1
mount /dev/pts >> /dev/null 2>&1
mount /proc >> /dev/null 2>&1
mount /sys >> /dev/null 2>&1
mount /tmp >> /dev/null 2>&1
mount /run >> /dev/null 2>&1
mount /sys/firmware/efivars >> /dev/null 2>&1
tput cuu1
echo "Mounting minimal fs: Done."
