#!/bin/sh
# @category FOGStubmenu
# @package  FOGUefi
# @author   Alexandre Botzung <alexandre.botzung@grandest.fr>
# @license  http://opensource.org/licenses/gpl-3.0 GPLv3
# @link     https://fogproject.org
# @desc     Runs "depmod" to ensure modules are ready
echo "Probing modules..."
depmod 2>&1
tput cuu1
echo "Probing modules : Done."
